# schema.graphql

type Query {
  product(ProductId: String!): Product
  productSearch(ProductName: String!): [Product]
  searchProducts(Keyword: String, Category: String, Region: String, MinPrice: Float, MaxPrice: Float, Sort: String): [Product]
  recentProducts(Limit: Float): [Product]
  userProducts(UserId: String!): [Product]
  user(UserId: String!): User
}

type Mutation {
  createUser(Email: String!, PasswordHash: String!, UserNickname: String!): User
  createProduct(UserId: String!, ProductName: String!, ProductDescription: String!, ProductPrice: Float!, ProductCategory: String!, ProductImage: [String!], PreferedLocation: String!, ProductRegion: String): Product
  updateProductStatus(ProductId: String!, UserId: String!, ProductStatus: String!): Product
  deleteProduct(ProductId: String!): Boolean
}

type Product {
  ProductId: String
  UserId: String
  ProductStatus: String
  ProductName: String
  ProductDescription: String
  ProductPrice: Float
  ProductCategory: String
  ProductRegion: String
  ProductImage: [String]
  PreferedLocation: String
  ProductCreatedAt: Float
  ProductUpdatedAt: Float
}

type User {
  UserId: String
  Email: String
  PasswordHash: String
  UserNickname: String
  ProfileImage: String
  PublishedQuantity: Float
  CreatedAt: Float
}
